# Generated by Django 4.0.2 on 2022-04-07 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='organization',
        ),
    ]
