# Generated by Django 4.0.2 on 2022-04-07 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_remove_role_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='rideexpensecostmatrix',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cost_matrices', to='organization.organization'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='fuel',
            unique_together={('organization', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='vehicle',
            unique_together={('organization', 'name')},
        ),
    ]
