# Generated by Django 4.0.2 on 2022-04-08 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_rideexpensecostmatrix_organization_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='latitude',
            field=models.DecimalField(decimal_places=7, max_digits=9),
        ),
        migrations.AlterField(
            model_name='location',
            name='longitude',
            field=models.DecimalField(decimal_places=7, max_digits=9),
        ),
        migrations.AlterField(
            model_name='location',
            name='radius',
            field=models.FloatField(default=50.0),
        ),
    ]
