# Generated by Django 4.0.2 on 2022-04-08 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0005_alter_location_latitude_alter_location_longitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rideexpensecostmatrix',
            name='fuel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cost_matrices', to='organization.fuel'),
        ),
        migrations.AlterField(
            model_name='rideexpensecostmatrix',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cost_matrices', to='organization.vehicle'),
        ),
        migrations.AlterUniqueTogether(
            name='rideexpensecostmatrix',
            unique_together={('fuel', 'vehicle')},
        ),
    ]
