# Generated by Django 4.0.2 on 2022-04-09 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0006_alter_rideexpensecostmatrix_fuel_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='location',
            unique_together={('organization', 'name')},
        ),
    ]
