# Generated by Django 4.0.2 on 2022-04-20 10:17

from django.db import migrations, models
import organization.models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0010_organization_address_organization_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=organization.models.rename_company_logo),
        ),
    ]
