# Generated by Django 4.0.2 on 2022-04-23 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0011_organization_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='auto_approval_limit',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
