# Generated by Django 4.0.2 on 2022-04-29 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0012_vehicle_auto_approval_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='email',
            field=models.CharField(blank=True, max_length=320, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
