# Generated by Django 4.0.2 on 2022-05-19 06:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0015_organizationlocation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='radius',
            field=models.FloatField(default=50.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxLengthValidator(5000.0)]),
        ),
    ]
