# Generated by Django 4.0.2 on 2022-05-19 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0016_alter_location_radius'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='location',
            constraint=models.CheckConstraint(check=models.Q(('radius__gte', 0.0), ('radius__lte', 5000.0)), name='location_radius_range'),
        ),
    ]
