# Generated by Django 4.0.4 on 2022-06-07 05:47

from django.db import migrations, models
import organization.models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0018_alter_location_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='settings',
            field=models.JSONField(blank=True, default=organization.models.default_org_settings, null=True),
        ),
    ]
