# Generated by Django 4.0.4 on 2022-06-07 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0019_alter_organization_settings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AlterModelOptions(
            name='designation',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AlterModelOptions(
            name='fuel',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AlterModelOptions(
            name='organizationlocation',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AlterModelOptions(
            name='rideexpensecostmatrix',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AlterModelOptions(
            name='vehicle',
            options={'ordering': ['-updated_at']},
        ),
    ]
