# Generated by Django 4.0.4 on 2022-06-09 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0020_alter_department_options_alter_designation_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='latitude',
            field=models.DecimalField(decimal_places=22, max_digits=26),
        ),
        migrations.AlterField(
            model_name='location',
            name='longitude',
            field=models.DecimalField(decimal_places=22, max_digits=26),
        ),
    ]
