# Generated by Django 4.0.4 on 2022-06-18 05:12

from django.db import migrations, models
import organization.models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0021_alter_location_latitude_alter_location_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='limit',
            field=models.JSONField(blank=True, default=organization.models.default_limit_settings, null=True),
        ),
    ]
