# Generated by Django 4.0.4 on 2022-06-28 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0022_organization_limit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizationlocation',
            name='email',
        ),
        migrations.RemoveField(
            model_name='organizationlocation',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='organizationlocation',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='organizationlocation',
            name='phone',
        ),
    ]
