# Generated by Django 4.0.4 on 2022-07-09 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0023_remove_organizationlocation_email_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['-updated_at'], 'verbose_name': 'System Location', 'verbose_name_plural': 'System Locations'},
        ),
    ]
