# Generated by Django 4.0.4 on 2022-07-26 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0019_alter_member_options'),
        ('organization', '0024_alter_location_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gcp_api_key', models.CharField(max_length=255)),
                ('short_gcp_api_key', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_connections', to='organization.organization')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='external_connections', to='member.member')),
            ],
        ),
    ]
