# Generated by Django 4.0.2 on 2022-10-03 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0025_externalconnection'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organization',
            old_name='city',
            new_name='location',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='address',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='domain',
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
