# Generated by Django 4.0.4 on 2023-02-01 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0026_rename_city_organization_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='enable_field_report',
            field=models.BooleanField(default=False),
        ),
    ]
