# Generated by Django 4.0.4 on 2023-02-10 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0027_department_enable_field_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='trip_rag_analysis',
            field=models.BooleanField(default=False),
        ),
    ]
