# Generated by Django 4.0.4 on 2023-02-10 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0028_organization_trip_rag_analysis'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='trip_rag_analysis',
        ),
    ]
