# Generated by Django 4.0.4 on 2023-03-03 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0030_alter_location_description_alter_location_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='source',
            field=models.CharField(choices=[('manual', 'Manual'), ('places_api', 'Places API')], default='manual', max_length=200),
        ),
    ]
