# Generated by Django 4.0.2 on 2023-03-21 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0031_location_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='create_trip_config_form',
            field=models.BooleanField(default=False),
        ),
    ]
