# Generated by Django 4.0.2 on 2023-03-22 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0032_department_create_trip_config_form'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='create_trip_config_form',
            new_name='enable_create_trip_config_form',
        ),
    ]
