# Generated by Django 4.0.2 on 2023-03-22 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0034_rename_enable_create_trip_config_form_department_enable_create_trip_form_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='enable_admin_report_form_config',
            field=models.BooleanField(default=False),
        ),
    ]
