# Generated by Django 4.0.2 on 2023-07-27 10:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0036_alter_department_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='radius',
            field=models.FloatField(default=50.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5000.0)]),
        ),
    ]
