# Generated by Django 4.0.2 on 2024-05-30 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0038_location_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='location', to='organization.department'),
        ),
    ]
