# Generated by Django 4.0.2 on 2024-06-04 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0019_alter_member_options'),
        ('organization', '0039_alter_location_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='department_head',
        ),
        migrations.AddField(
            model_name='department',
            name='department_head',
            field=models.ManyToManyField(related_name='department_head', to='member.Member'),
        ),
    ]
