# Generated by Django 4.0.2 on 2024-06-04 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0019_alter_member_options'),
        ('organization', '0040_remove_department_department_head_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='department_head',
            field=models.ManyToManyField(blank=True, related_name='department_head', to='member.Member'),
        ),
    ]
