# Generated by Django 4.0.2 on 2024-08-20 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0041_alter_department_department_head'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=50),
        ),
    ]
