# Generated by Django 4.0.4 on 2022-06-09 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0019_alter_member_options'),
        ('export', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exportrequest',
            name='user',
        ),
        migrations.AddField(
            model_name='exportrequest',
            name='member',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='export_requests', to='member.member'),
            preserve_default=False,
        ),
    ]
