# Generated by Django 4.0.4 on 2022-07-03 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('export', '0002_remove_exportrequest_user_exportrequest_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exportrequest',
            name='content',
            field=models.TextField(),
        ),
    ]
