# Generated by Django 4.0.2 on 2022-04-07 10:20

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/images/fr/')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_images', to='member.member')),
            ],
        ),
    ]
