# Generated by Django 4.0.2 on 2022-04-07 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_role'),
        ('member', '0003_memberimages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='organization.role'),
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
