# Generated by Django 4.0.2 on 2022-04-07 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0004_alter_member_role_delete_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='managers', to='member.member'),
        ),
    ]
