# Generated by Django 4.0.2 on 2022-04-08 08:38

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0005_alter_location_latitude_alter_location_longitude_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('member', '0005_member_manager'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='member',
            unique_together={('organization', 'user')},
        ),
    ]
