# Generated by Django 4.0.2 on 2022-04-09 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0007_alter_member_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='managed_members', to='member.member'),
        ),
    ]
