# Generated by Django 4.0.2 on 2022-04-11 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0008_alter_member_manager'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MemberImages',
            new_name='MemberImage',
        ),
    ]
