# Generated by Django 4.0.2 on 2022-04-11 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0009_rename_memberimages_memberimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberimage',
            name='encoding',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
