# Generated by Django 4.0.2 on 2022-04-12 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0010_memberimage_encoding'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='media/images/profiles/'),
        ),
    ]
