# Generated by Django 4.0.2 on 2022-04-13 10:18

from django.db import migrations, models
import member.models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0011_profile_address_profile_dob_profile_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=member.models.rename_member_fr_images),
        ),
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=member.models.rename_member_profile_images),
        ),
    ]
