# Generated by Django 4.0.2 on 2022-05-07 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0014_designation_department'),
        ('member', '0012_alter_memberimage_image_alter_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='members', to='organization.department'),
        ),
        migrations.AddField(
            model_name='member',
            name='designation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='members', to='organization.designation'),
        ),
    ]
