# Generated by Django 4.0.2 on 2022-05-09 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0015_organizationlocation'),
        ('member', '0013_member_department_member_designation'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='organization_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='members', to='organization.organizationlocation'),
        ),
    ]
