# Generated by Django 4.0.2 on 2022-05-12 05:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0014_member_organization_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberimage',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
