# Generated by Django 4.0.2 on 2022-05-12 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0015_memberimage_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberimage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
