# Generated by Django 4.0.2 on 2022-05-14 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0016_alter_memberimage_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='memberimage',
            options={'ordering': ['-created_at']},
        ),
    ]
