# Generated by Django 4.0.2 on 2022-06-03 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0017_alter_memberimage_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='employee_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddConstraint(
            model_name='member',
            constraint=models.UniqueConstraint(fields=('organization', 'employee_id'), name='unique_employee_id'),
        ),
    ]
