# Generated by Django 4.0.4 on 2022-06-07 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0018_member_employee_id_member_unique_employee_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'ordering': ['-updated_at']},
        ),
    ]
