# Generated by Django 4.0.2 on 2022-04-07 10:00

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RideExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('vehicle_mode', models.CharField(choices=[('self', 'Self'), ('hire', 'Hire')], max_length=200)),
                ('amount', models.FloatField()),
                ('amount_breakdown', models.JSONField(blank=True, default=dict, null=True)),
                ('status', models.CharField(choices=[('approved', 'Approved'), ('denied', 'Denied')], max_length=200)),
                ('claim_reimbursement', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='RideExpenseComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('comments', models.JSONField(blank=True, default=dict, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RideExpenseDocs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/images/')),
                ('document', models.FileField(blank=True, null=True, upload_to='media/files/')),
                ('ride_expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ride_expense_docs', to='expense.rideexpense')),
            ],
        ),
    ]
