# Generated by Django 4.0.2 on 2022-04-07 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('member', '0001_initial'),
        ('organization', '0001_initial'),
        ('trip', '0001_initial'),
        ('expense', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rideexpensecomment',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ride_expense_comments', to='member.member'),
        ),
        migrations.AddField(
            model_name='rideexpensecomment',
            name='ride_expense',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ride_expense_comments', to='expense.rideexpense'),
        ),
        migrations.AddField(
            model_name='rideexpense',
            name='fuel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ride_expenses', to='organization.fuel'),
        ),
        migrations.AddField(
            model_name='rideexpense',
            name='trip',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ride_expense', to='trip.trip'),
        ),
        migrations.AddField(
            model_name='rideexpense',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ride_expenses', to='organization.vehicle'),
        ),
    ]
