# Generated by Django 4.0.2 on 2022-04-07 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rideexpensedocs',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='media/files/ride_expense/'),
        ),
        migrations.AlterField(
            model_name='rideexpensedocs',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/images/ride_expense/'),
        ),
    ]
