# Generated by Django 4.0.2 on 2022-04-08 04:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_rideexpensecostmatrix_organization_and_more'),
        ('expense', '0003_alter_rideexpensedocs_document_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rideexpense',
            name='fuel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='ride_expenses', to='organization.fuel'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rideexpense',
            name='vehicle',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='ride_expenses', to='organization.vehicle'),
            preserve_default=False,
        ),
    ]
