# Generated by Django 4.0.2 on 2022-04-08 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0004_alter_rideexpense_fuel_alter_rideexpense_vehicle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rideexpense',
            name='amount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
