# Generated by Django 4.0.2 on 2022-04-08 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0006_alter_rideexpensecostmatrix_fuel_and_more'),
        ('expense', '0005_alter_rideexpense_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rideexpense',
            name='fuel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ride_expenses', to='organization.fuel'),
        ),
        migrations.AlterField(
            model_name='rideexpense',
            name='status',
            field=models.CharField(blank=True, choices=[('approved', 'Approved'), ('denied', 'Denied')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='rideexpense',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ride_expenses', to='organization.vehicle'),
        ),
        migrations.AlterField(
            model_name='rideexpense',
            name='vehicle_mode',
            field=models.CharField(blank=True, choices=[('self', 'Self'), ('hire', 'Hire')], max_length=200, null=True),
        ),
    ]
