# Generated by Django 4.0.2 on 2022-04-09 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0006_alter_rideexpense_fuel_alter_rideexpense_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rideexpense',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('approval_rejected ', 'Approval Rejected'), ('reimbursement_rejected', 'Reimbursement Rejected'), ('reimbursed', 'Reimbursed'), ('closed', 'Closed')], default='draft', max_length=200),
        ),
    ]
