# Generated by Django 4.0.2 on 2022-06-02 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0017_alter_memberimage_options'),
        ('expense', '0010_paymentmode_rideexpense_payment_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='rideexpense',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ride_expenses_approved_by', to='member.member'),
        ),
        migrations.AddField(
            model_name='rideexpense',
            name='reimbursed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ride_expenses_reimbursed_by', to='member.member'),
        ),
    ]
