# Generated by Django 4.0.4 on 2022-06-04 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0011_rideexpense_approved_by_rideexpense_reimbursed_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='rideexpense',
            name='reimbursement_amount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
