# Generated by Django 4.0.4 on 2022-06-07 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0012_rideexpense_reimbursement_amount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rideexpense',
            options={'ordering': ['-updated_at']},
        ),
    ]
