# Generated by Django 4.0.4 on 2022-06-08 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0013_alter_rideexpense_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rideexpensecomment',
            name='comments',
            field=models.CharField(default='a', max_length=200),
            preserve_default=False,
        ),
    ]
