# Generated by Django 4.0.4 on 2022-06-11 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0014_alter_rideexpensecomment_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='rideexpensecomment',
            name='status',
            field=models.CharField(default='rejected', max_length=200),
            preserve_default=False,
        ),
    ]
