# Generated by Django 4.0.4 on 2022-06-16 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0015_rideexpensecomment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rideexpense',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending_approval', 'Pending Approval'), ('pending_reimbursement', 'Pending Reimbursement'), ('approval_rejected ', 'Approval Rejected'), ('reimbursement_rejected', 'Reimbursement Rejected'), ('reimbursed', 'Reimbursed'), ('closed', 'Closed')], default='draft', max_length=200),
        ),
    ]
