# Generated by Django 4.0.4 on 2022-06-17 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0016_alter_rideexpense_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='rideexpense',
            name='auto_approved',
            field=models.BooleanField(default=True),
        ),
    ]
