# Generated by Django 4.0.4 on 2022-06-20 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0017_rideexpense_auto_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rideexpense',
            name='auto_approved',
            field=models.BooleanField(default=False),
        ),
    ]
