# Generated by Django 4.0.4 on 2022-07-01 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0018_alter_rideexpense_auto_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rideexpense',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='rideexpense',
            name='updated_at',
            field=models.DateTimeField(),
        ),
    ]
