# Generated by Django 4.0.4 on 2022-07-01 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0020_alter_rideexpense_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rideexpense',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='rideexpense',
            name='updated_at',
            field=models.DateTimeField(),
        ),
    ]
