# Generated by Django 4.0.4 on 2022-07-04 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0021_alter_rideexpense_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rideexpense',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='rideexpense',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
