# Generated by Django 4.0.4 on 2022-07-05 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0023_alter_rideexpense_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rideexpense',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='rideexpense',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending_approval', 'Pending Approval'), ('pending_reimbursement', 'Pending Reimbursement'), ('approval_rejected', 'Approval Rejected'), ('reimbursement_rejected', 'Reimbursement Rejected'), ('reimbursed', 'Reimbursed'), ('closed', 'Closed')], default='draft', max_length=200),
        ),
        migrations.AlterField(
            model_name='rideexpense',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
