# Generated by Django 4.0.2 on 2023-04-17 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0024_alter_rideexpense_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmode',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rideexpense',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
