# Generated by Django 4.0.2 on 2022-04-07 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripscan',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/images/scans/'),
        ),
    ]
