# Generated by Django 4.0.2 on 2022-04-07 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0002_alter_tripscan_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='trip_type',
            field=models.CharField(choices=[('self', 'Self'), ('assigned', 'Assigned')], max_length=200),
        ),
    ]
