# Generated by Django 4.0.2 on 2022-04-08 03:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0003_alter_trip_trip_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripscan',
            name='trip',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='trip_scans', to='trip.trip'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trip',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('starte ', 'Started'), ('ended', 'Ended'), ('ride_expense_created', 'Ride Expense Created'), ('outside_geo_fencing', 'Outside Geo Fencing')], max_length=200),
        ),
    ]
