# Generated by Django 4.0.2 on 2022-04-08 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0004_tripscan_trip_alter_trip_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tripscan',
            name='trip',
        ),
    ]
