# Generated by Django 4.0.2 on 2022-04-08 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0005_remove_tripscan_trip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripdetails',
            name='duration',
            field=models.TimeField(blank=True, max_length=200, null=True),
        ),
    ]
