# Generated by Django 4.0.2 on 2022-04-08 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0006_alter_rideexpensecostmatrix_fuel_and_more'),
        ('trip', '0006_alter_tripdetails_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='organization.organization'),
            preserve_default=False,
        ),
    ]
