# Generated by Django 4.0.2 on 2022-04-08 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0007_trip_organization'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trip',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AlterField(
            model_name='trip',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('started ', 'Started'), ('ended', 'Ended'), ('ride_expense_created', 'Ride Expense Created'), ('outside_geo_fencing', 'Outside Geo Fencing'), ('canceled', 'Canceled')], max_length=200),
        ),
    ]
