# Generated by Django 4.0.2 on 2022-04-11 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0007_alter_location_unique_together'),
        ('trip', '0008_alter_trip_options_alter_trip_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='end_location_ptr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trips_end_location', to='organization.location'),
        ),
        migrations.AddField(
            model_name='trip',
            name='start_location_ptr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trips_start_location', to='organization.location'),
        ),
    ]
