# Generated by Django 4.0.2 on 2022-04-11 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0009_trip_end_location_ptr_trip_start_location_ptr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('started', 'Started'), ('ended', 'Ended'), ('ride_expense_created', 'Ride Expense Created'), ('outside_geo_fencing', 'Outside Geo Fencing'), ('canceled', 'Canceled')], max_length=200),
        ),
    ]
