# Generated by Django 4.0.2 on 2022-04-11 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0010_alter_trip_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripscan',
            name='comments',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
