# Generated by Django 4.0.2 on 2022-04-12 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0012_tripdetails_updated_at_tripscan_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripscan',
            name='time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
