# Generated by Django 4.0.2 on 2022-04-14 07:10

from django.db import migrations, models
import trip.models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0013_alter_tripscan_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripscan',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=trip.models.rename_trip_scan_images),
        ),
    ]
