# Generated by Django 4.0.2 on 2022-04-28 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0014_alter_tripscan_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripscan',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
