# Generated by Django 4.0.2 on 2022-04-29 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0015_tripscan_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tripscan',
            old_name='comments',
            new_name='notes',
        ),
    ]
