# Generated by Django 4.0.2 on 2022-05-10 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0016_rename_comments_tripscan_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='remarks',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
