# Generated by Django 4.0.2 on 2022-05-11 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0017_trip_remarks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='remarks',
        ),
    ]
