# Generated by Django 4.0.2 on 2022-05-26 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0018_remove_trip_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
