# Generated by Django 4.0.2 on 2022-06-02 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0019_trip_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=200),
        ),
        migrations.AddField(
            model_name='trip',
            name='time',
            field=models.DateField(blank=True, null=True),
        ),
    ]
