# Generated by Django 4.0.2 on 2022-06-02 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0020_trip_date_trip_priority_trip_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='time',
        ),
    ]
