# Generated by Django 4.0.2 on 2022-06-02 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0021_remove_trip_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
