# Generated by Django 4.0.2 on 2022-06-04 05:30

from django.db import migrations, models
import django.db.models.deletion
import trip.models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0018_member_employee_id_member_unique_employee_id'),
        ('organization', '0018_alter_location_email'),
        ('trip', '0023_alter_trip_priority_triptemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='triptemplate',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trip_templates_assigned_to', to='member.member'),
        ),
        migrations.AddField(
            model_name='triptemplate',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='triptemplate',
            name='end_location',
            field=models.JSONField(default=trip.models.default_location),
        ),
        migrations.AddField(
            model_name='triptemplate',
            name='end_location_ptr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trip_templates_end_location', to='organization.location'),
        ),
        migrations.AddField(
            model_name='triptemplate',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='low', max_length=200),
        ),
        migrations.AddField(
            model_name='triptemplate',
            name='start_location',
            field=models.JSONField(default=trip.models.default_location),
        ),
        migrations.AddField(
            model_name='triptemplate',
            name='start_location_ptr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trip_templates_start_location', to='organization.location'),
        ),
        migrations.AddField(
            model_name='triptemplate',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('started', 'Started'), ('ended', 'Ended'), ('ride_expense_created', 'Ride Expense Created'), ('outside_geo_fencing', 'Outside Geo Fencing'), ('canceled', 'Canceled')], default='created', max_length=200),
        ),
    ]
