# Generated by Django 4.0.4 on 2022-06-04 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0024_triptemplate_assigned_to_triptemplate_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('started', 'Started'), ('ended', 'Ended'), ('ride_expense_created', 'Ride Expense Created'), ('outside_geo_fencing', 'Outside Geo Fencing'), ('cancelled ', 'Cancelled ')], default='created', max_length=200),
        ),
    ]
