# Generated by Django 4.0.4 on 2022-06-07 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0025_alter_trip_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='is_outside_geo_fencing',
            field=models.BooleanField(default=False),
        ),
    ]
