# Generated by Django 4.0.4 on 2022-06-08 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0026_trip_is_outside_geo_fencing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('started', 'Started'), ('ended', 'Ended'), ('ride_expense_created', 'Ride Expense Created'), ('cancelled ', 'Cancelled ')], default='created', max_length=200),
        ),
    ]
