# Generated by Django 4.0.4 on 2022-06-11 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0021_alter_location_latitude_alter_location_longitude'),
        ('trip', '0027_alter_trip_status'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='trip',
            unique_together={('organization', 'name')},
        ),
    ]
