# Generated by Django 4.0.4 on 2022-06-14 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0028_alter_trip_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='priority',
            field=models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], max_length=200, null=True),
        ),
    ]
