# Generated by Django 4.0.4 on 2022-06-17 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0029_alter_trip_priority'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tripdetails',
            options={'verbose_name_plural': 'Trip Details'},
        ),
    ]
