# Generated by Django 4.0.4 on 2022-06-24 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0030_alter_tripdetails_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripdetails',
            name='estimated_distance',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tripdetails',
            name='estimated_duration',
            field=models.TimeField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('started', 'Started'), ('ended', 'Ended'), ('ride_expense_created', 'Ride Expense Created'), ('cancelled', 'Cancelled')], default='created', max_length=200),
        ),
    ]
