# Generated by Django 4.0.4 on 2022-07-14 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0035_alter_trip_created_at_alter_trip_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripdetails',
            name='duration',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
