# Generated by Django 4.0.2 on 2022-12-09 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0036_alter_tripdetails_duration'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='trip',
            unique_together=set(),
        ),
    ]
