# Generated by Django 4.0.2 on 2022-12-21 07:47

from django.db import migrations, models
import trip.models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0037_alter_trip_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='trip_sync_comments',
            field=models.JSONField(default=trip.models.trip_sync_comments),
        ),
    ]
