# Generated by Django 4.0.4 on 2023-02-07 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0038_trip_trip_sync_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('started', 'Started'), ('ended', 'Ended'), ('field_report_submitted', 'Field Report Submitted'), ('ride_expense_created', 'Ride Expense Created'), ('cancelled', 'Cancelled')], default='created', max_length=200),
        ),
    ]
