# Generated by Django 4.0.4 on 2023-02-10 06:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0039_alter_trip_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='planned_end_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='trip',
            name='planned_start_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
