# Generated by Django 4.0.4 on 2023-02-10 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0040_trip_planned_end_time_trip_planned_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='planned_end_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='trip',
            name='planned_start_time',
            field=models.DateTimeField(),
        ),
    ]
