# Generated by Django 4.0.4 on 2023-02-10 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0041_alter_trip_planned_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='planned_end_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='planned_start_time',
            field=models.DateTimeField(null=True),
        ),
    ]
