# Generated by Django 4.0.2 on 2023-04-17 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0043_alter_trip_planned_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='triptemplate',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
