# Generated by Django 4.0.2 on 2023-08-24 08:15

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0045_trip_force_trip_sync_logs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='force_trip_sync_logs',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(max_length=200), blank=True, null=True, size=None),
        ),
    ]
