# Generated by Django 4.0.4 on 2023-02-01 09:15

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trip', '0038_trip_trip_sync_comments'),
        ('organization', '0027_department_enable_field_report'),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldReportFormBuilder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('field_1', models.JSONField(null=True)),
                ('field_2', models.JSONField(null=True)),
                ('field_3', models.JSONField(null=True)),
                ('field_4', models.JSONField(null=True)),
                ('field_5', models.JSONField(null=True)),
                ('field_6', models.JSONField(null=True)),
                ('field_7', models.JSONField(null=True)),
                ('field_8', models.JSONField(null=True)),
                ('field_9', models.JSONField(null=True)),
                ('field_10', models.JSONField(null=True)),
                ('field_11', models.JSONField(null=True)),
                ('field_12', models.JSONField(null=True)),
                ('field_13', models.JSONField(null=True)),
                ('field_14', models.JSONField(null=True)),
                ('field_15', models.JSONField(null=True)),
                ('field_16', models.JSONField(null=True)),
                ('field_17', models.JSONField(null=True)),
                ('field_18', models.JSONField(null=True)),
                ('field_19', models.JSONField(null=True)),
                ('department', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='organization.department')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.organization')),
            ],
        ),
        migrations.CreateModel(
            name='FieldReportFormSubmissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('field_1', models.JSONField(null=True)),
                ('field_2', models.JSONField(null=True)),
                ('field_3', models.JSONField(null=True)),
                ('field_4', models.JSONField(null=True)),
                ('field_5', models.JSONField(null=True)),
                ('field_6', models.JSONField(null=True)),
                ('field_7', models.JSONField(null=True)),
                ('field_8', models.JSONField(null=True)),
                ('field_9', models.JSONField(null=True)),
                ('field_10', models.JSONField(null=True)),
                ('field_11', models.JSONField(null=True)),
                ('field_12', models.JSONField(null=True)),
                ('field_13', models.JSONField(null=True)),
                ('field_14', models.JSONField(null=True)),
                ('field_15', models.JSONField(null=True)),
                ('field_16', models.JSONField(null=True)),
                ('field_17', models.JSONField(null=True)),
                ('field_18', models.JSONField(null=True)),
                ('field_19', models.JSONField(null=True)),
                ('department', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='organization.department')),
                ('field_report_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form_builder.fieldreportformbuilder')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.organization')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trip.trip')),
            ],
        ),
    ]
