# Generated by Django 4.0.4 on 2023-02-01 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_builder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldreportformbuilder',
            name='field_20',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='fieldreportformsubmissions',
            name='field_20',
            field=models.JSONField(null=True),
        ),
    ]
