# Generated by Django 4.0.4 on 2023-02-01 11:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('form_builder', '0002_fieldreportformbuilder_field_20_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldreportformbuilder',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fieldreportformbuilder',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='fieldreportformsubmissions',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fieldreportformsubmissions',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
