# Generated by Django 4.0.4 on 2023-02-01 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0038_trip_trip_sync_comments'),
        ('organization', '0027_department_enable_field_report'),
        ('form_builder', '0003_fieldreportformbuilder_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldreportformsubmissions',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.department'),
        ),
        migrations.AlterField(
            model_name='fieldreportformsubmissions',
            name='trip',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='trip.trip'),
        ),
    ]
