# Generated by Django 4.0.4 on 2023-02-01 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0027_department_enable_field_report'),
        ('trip', '0038_trip_trip_sync_comments'),
        ('form_builder', '0004_alter_fieldreportformsubmissions_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldreportformbuilder',
            name='department',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='field_report_form_builder', to='organization.department'),
        ),
        migrations.AlterField(
            model_name='fieldreportformbuilder',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_report_form_builder', to='organization.organization'),
        ),
        migrations.AlterField(
            model_name='fieldreportformsubmissions',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_report_form_submission', to='organization.department'),
        ),
        migrations.AlterField(
            model_name='fieldreportformsubmissions',
            name='field_report_form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_report_form_submission', to='form_builder.fieldreportformbuilder'),
        ),
        migrations.AlterField(
            model_name='fieldreportformsubmissions',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_report_form_submission', to='organization.organization'),
        ),
        migrations.AlterField(
            model_name='fieldreportformsubmissions',
            name='trip',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='field_report_form_submission', to='trip.trip'),
        ),
    ]
