# Generated by Django 4.0.4 on 2023-02-01 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_builder', '0005_alter_fieldreportformbuilder_department_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fieldreportformbuilder',
            name='field_1',
        ),
        migrations.AlterField(
            model_name='fieldreportformbuilder',
            name='field_10',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fieldreportformbuilder',
            name='field_11',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fieldreportformbuilder',
            name='field_12',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fieldreportformbuilder',
            name='field_13',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fieldreportformbuilder',
            name='field_14',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fieldreportformbuilder',
            name='field_15',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fieldreportformbuilder',
            name='field_16',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fieldreportformbuilder',
            name='field_17',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fieldreportformbuilder',
            name='field_18',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fieldreportformbuilder',
            name='field_19',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fieldreportformbuilder',
            name='field_2',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fieldreportformbuilder',
            name='field_20',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fieldreportformbuilder',
            name='field_3',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fieldreportformbuilder',
            name='field_4',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fieldreportformbuilder',
            name='field_5',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fieldreportformbuilder',
            name='field_6',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fieldreportformbuilder',
            name='field_7',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fieldreportformbuilder',
            name='field_8',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fieldreportformbuilder',
            name='field_9',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fieldreportformsubmissions',
            name='field_1',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fieldreportformsubmissions',
            name='field_10',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fieldreportformsubmissions',
            name='field_11',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fieldreportformsubmissions',
            name='field_12',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fieldreportformsubmissions',
            name='field_13',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fieldreportformsubmissions',
            name='field_14',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fieldreportformsubmissions',
            name='field_15',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fieldreportformsubmissions',
            name='field_16',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fieldreportformsubmissions',
            name='field_17',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fieldreportformsubmissions',
            name='field_18',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fieldreportformsubmissions',
            name='field_19',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fieldreportformsubmissions',
            name='field_2',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fieldreportformsubmissions',
            name='field_20',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fieldreportformsubmissions',
            name='field_3',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fieldreportformsubmissions',
            name='field_4',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fieldreportformsubmissions',
            name='field_5',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fieldreportformsubmissions',
            name='field_6',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fieldreportformsubmissions',
            name='field_7',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fieldreportformsubmissions',
            name='field_8',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fieldreportformsubmissions',
            name='field_9',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
