# Generated by Django 4.0.4 on 2023-02-01 19:06

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0027_department_enable_field_report'),
        ('form_builder', '0006_remove_fieldreportformbuilder_field_1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldReportFormConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('field_2', models.JSONField(blank=True, null=True)),
                ('field_3', models.JSONField(blank=True, null=True)),
                ('field_4', models.JSONField(blank=True, null=True)),
                ('field_5', models.JSONField(blank=True, null=True)),
                ('field_6', models.JSONField(blank=True, null=True)),
                ('field_7', models.JSONField(blank=True, null=True)),
                ('field_8', models.JSONField(blank=True, null=True)),
                ('field_9', models.JSONField(blank=True, null=True)),
                ('field_10', models.JSONField(blank=True, null=True)),
                ('field_11', models.JSONField(blank=True, null=True)),
                ('field_12', models.JSONField(blank=True, null=True)),
                ('field_13', models.JSONField(blank=True, null=True)),
                ('field_14', models.JSONField(blank=True, null=True)),
                ('field_15', models.JSONField(blank=True, null=True)),
                ('field_16', models.JSONField(blank=True, null=True)),
                ('field_17', models.JSONField(blank=True, null=True)),
                ('field_18', models.JSONField(blank=True, null=True)),
                ('field_19', models.JSONField(blank=True, null=True)),
                ('field_20', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='field_report_form_config', to='organization.department')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_report_form_config', to='organization.organization')),
            ],
        ),
        migrations.AlterField(
            model_name='fieldreportformsubmissions',
            name='field_report_form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_report_form_submission', to='form_builder.fieldreportformconfig'),
        ),
        migrations.DeleteModel(
            name='FieldReportFormBuilder',
        ),
    ]
