# Generated by Django 4.0.4 on 2023-02-02 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_builder', '0007_fieldreportformconfig_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldreportformconfig',
            name='field_1',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
