# Generated by Django 4.0.4 on 2023-02-02 12:57

from django.db import migrations, models
import django.db.models.deletion
import form_builder.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('form_builder', '0008_fieldreportformconfig_field_1'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldreportformconfig',
            name='attachment',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='FieldReportFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('file', models.FileField(upload_to=form_builder.models.rename_field_report_file)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('field_report_form_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_report_file', to='form_builder.fieldreportformconfig')),
            ],
        ),
    ]
