# Generated by Django 4.0.4 on 2023-02-02 16:38

from django.db import migrations, models
import django.db.models.deletion
import form_builder.models


class Migration(migrations.Migration):

    dependencies = [
        ('form_builder', '0009_fieldreportformconfig_attachment_fieldreportfile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fieldreportfile',
            name='field_report_form_config',
        ),
        migrations.AddField(
            model_name='fieldreportfile',
            name='field_report_form_submission',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='field_report_file', to='form_builder.fieldreportformsubmissions'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fieldreportfile',
            name='file',
            field=models.FileField(upload_to=form_builder.models.rename_field_report_file, validators=[form_builder.models.validate_file_extension]),
        ),
    ]
