# Generated by Django 4.0.4 on 2023-02-07 05:33

from django.db import migrations, models
import form_builder.models


class Migration(migrations.Migration):

    dependencies = [
        ('form_builder', '0010_remove_fieldreportfile_field_report_form_config_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldreportformsubmissions',
            name='attachment',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fieldreportfile',
            name='file',
            field=models.FileField(upload_to=form_builder.models.rename_field_report_file, validators=[form_builder.models.validate_file_extension, form_builder.models.file_size]),
        ),
    ]
