# Generated by Django 4.0.2 on 2023-03-21 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('form_builder', '0013_createtripformsubmissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createtripformsubmissions',
            name='create_trip_form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='create_trip_form_submissions', to='form_builder.createtripformconfig'),
        ),
    ]
