# Generated by Django 4.0.2 on 2023-03-22 17:51

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0034_rename_enable_create_trip_config_form_department_enable_create_trip_form_config'),
        ('form_builder', '0014_alter_createtripformsubmissions_create_trip_form'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminReportFormConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('field_1', models.JSONField(blank=True, null=True)),
                ('field_2', models.JSONField(blank=True, null=True)),
                ('field_3', models.JSONField(blank=True, null=True)),
                ('field_4', models.JSONField(blank=True, null=True)),
                ('field_5', models.JSONField(blank=True, null=True)),
                ('field_6', models.JSONField(blank=True, null=True)),
                ('field_7', models.JSONField(blank=True, null=True)),
                ('field_8', models.JSONField(blank=True, null=True)),
                ('field_9', models.JSONField(blank=True, null=True)),
                ('field_10', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_report_form_config', to='organization.department')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_report_form_config', to='organization.organization')),
            ],
        ),
    ]
