# Generated by Django 4.0.2 on 2023-03-22 18:48

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0043_alter_trip_planned_end_time_and_more'),
        ('organization', '0035_department_enable_admin_report_form_config'),
        ('form_builder', '0015_adminreportformconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminReportFormSubmissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('field_1', models.JSONField(blank=True, null=True)),
                ('field_2', models.JSONField(blank=True, null=True)),
                ('field_3', models.JSONField(blank=True, null=True)),
                ('field_4', models.JSONField(blank=True, null=True)),
                ('field_5', models.JSONField(blank=True, null=True)),
                ('field_6', models.JSONField(blank=True, null=True)),
                ('field_7', models.JSONField(blank=True, null=True)),
                ('field_8', models.JSONField(blank=True, null=True)),
                ('field_9', models.JSONField(blank=True, null=True)),
                ('field_10', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin_report_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_report_form_submissions', to='form_builder.adminreportformconfig')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_report_form_submissions', to='organization.department')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_report_form_submissions', to='organization.organization')),
                ('trip', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_report_form_submissions', to='trip.trip')),
            ],
        ),
    ]
