from django.urls import path

from account.views import user_views
from expense.views import approval_views, expense_views, payment_mode_views
from export.views import export_request_views
# import form_builder
from member.views import member_views, member_misc_views, member_report_views
from organization.views import org_trip_views, org_views
from trip.views import trip_details_views, trip_views, trip_template_views
from form_builder.views import form_builder, form_submission, create_trip_field_report_config
from form_builder.views import admin_report_form_config

urlpatterns = [
    # ! User
    path(
        "login/",
        user_views.LoginAPI.as_view(),
    ),
    path(
        "logout/",
        user_views.LogoutAPI.as_view(),
    ),
    path(
        "get-csrf/",
        user_views.get_csrf,
    ),
    path(
        "user-registration/",
        user_views.UserRegistrationAPI.as_view(),
    ),
    path(
        "user-activation/",
        user_views.UserActivationAPI.as_view(),
    ),
    path(
        "change-password/",
        user_views.ChangePasswordAPI.as_view(),
    ),
    path(
        "forgot-password/",
        user_views.ForgotPasswordAPI.as_view(),
    ),
    path(
        "password-reset/",
        user_views.PasswordResetAPI.as_view(),
    ),
    path(
        "set-password/<uuid:uuid>/",
        user_views.SetPasswordAPI.as_view(),
    ),
    path(
        "user-data/",
        user_views.UserDataAPI.as_view(),
    ),
    path(
        "test/",
        user_views.TestAPI.as_view(),
    ),
    path(
        "fetch-file/<path:path>/",
        user_views.FetchFileAPI.as_view(),
    ),
    # ! Member
    path(
        "members/",
        member_views.AllMembersAPI.as_view(),
    ),
    path("members/<uuid:uuid>/", member_views.MemberAPI.as_view()),
    path(
        "members/<uuid:uuid>/role/",
        member_misc_views.MemberRoleAPI.as_view(),
    ),
    path(
        "members/<uuid:uuid>/manager/",
        member_views.MemberManagerAPI.as_view(),
    ),
    path(
        "members/images/",
        member_views.MembersAllImagesAPI.as_view(),
    ),
    path(
        "members/images/<uuid:uuid>/",
        member_views.MemberImageAPI.as_view(),
    ),
    path(
        "members/<uuid:uuid>/trips/",
        member_misc_views.MemberTripsAPI.as_view(),
    ),
    path(
        "members/<uuid:uuid>/designation/",
        member_misc_views.MemberDesignationAPI.as_view(),
    ),
    path(
        "members/<uuid:uuid>/department/",
        member_misc_views.MemberDepartmentAPI.as_view(),
    ),
    path(
        "members/<uuid:uuid>/organization-locations/",
        member_misc_views.MemberOrganizationLocationAPI.as_view(),
    ),
    path(
        "profile/",
        member_views.MemberProfileAPI.as_view(),
    ),
    path(
        "members/last-location/",
        member_misc_views.MemberLastLocationAPI.as_view(),
    ),
    path(
        "members/upload-csv/",
        member_views.MembersUploadCSVAPI.as_view(),
    ),
    path(
        "assigned-members/",
        member_views.AssignedMembersAPI.as_view(),
    ),
    path(
        "trip-status/",
        member_misc_views.MemberTripStatusAPI.as_view(),
    ),
    path(
        "statistics/",
        member_report_views.StatisticsAPI.as_view(),
    ),
    path(
        "report/",
        member_report_views.ReportAPI.as_view(),
    ),
    path(
        "member-report/",
        member_report_views.MemberReportAPI.as_view(),
    ),
    path(
        "dashboard/",
        member_report_views.DashboardAPI.as_view(),
        name="api-dashboard-view",
    ),
    # ! Organization
    path(
        "organization/",
        org_views.OrganizationAPI.as_view(),
    ),
    path(
        "vehicles/",
        org_trip_views.AllVehiclesAPI.as_view(),
    ),
    path(
        "vehicles/<uuid:uuid>/",
        org_trip_views.VehicleAPI.as_view(),
    ),
    path(
        "fuels/",
        org_trip_views.AllFuelsAPI.as_view(),
    ),
    path(
        "fuels/<uuid:uuid>/",
        org_trip_views.FuelAPI.as_view(),
    ),
    path(
        "cost-matrix/",
        org_trip_views.AllRideExpenseCostMatrixAPI.as_view(),
    ),
    path(
        "cost-matrix/<uuid:uuid>/",
        org_trip_views.RideExpenseCostMatrixAPI.as_view(),
    ),
    path(
        "roles/",
        org_views.AllRolesAPI.as_view(),
    ),
    path(
        "roles/<uuid:uuid>/",
        org_views.RoleAPI.as_view(),
    ),
    path(
        "departments/",
        org_views.AllDepartmentsAPI.as_view(),
    ),
    path(
        "departments/<uuid:uuid>/",
        org_views.DepartmentAPI.as_view(),
    ),
    path(
        "departments/create_trip_config_form/<uuid:uuid>/",
        org_views.DepartmentPatchAPI.as_view(),
    ),
    path(
        "departments/admin_report_config_form/<uuid:uuid>/",
        org_views.DepartmentAdminReportPatchAPI.as_view(),
    ),
    path(
        "departments/upload-csv/",
        org_views.DepartmentUploadCSVAPI.as_view(),
    ),
    path(
        "designations/",
        org_views.AllDesignationsAPI.as_view(),
    ),
    path(
        "designations/<uuid:uuid>/",
        org_views.DesignationAPI.as_view(),
    ),
    path(
        "organization-locations/",
        org_views.AllOrganizationLocationsAPI.as_view(),
    ),
    path(
        "organization-locations/<uuid:uuid>/",
        org_views.OrganizationLocationAPI.as_view(),
    ),
    # Permission (admin role)
    path(
        "organization/external-connection/",
        org_views.ExternalConnectionAPIView.as_view(),
    ),
    path(
        "external-connection/active/",
        org_views.IsActiveExternalConnectionAPIView.as_view(),
    ),

    path(
        "scan-settings/",
        org_trip_views.ScanSettingsAPI.as_view(),
    ),
    path(
        "ride-expense-settings/",
        org_trip_views.RideExpenseSettingsAPI.as_view(),
    ),
    path(
        "locations/",
        org_trip_views.AllLocationsAPI.as_view(),
    ),
    path(
        "locations/<uuid:uuid>/",
        org_trip_views.LocationAPI.as_view(),
    ),
    path(
        "locations/upload-csv/",
        org_trip_views.LocationsUploadCSVAPI.as_view(),
    ),

    path(
        "allowed-locations/",
        org_trip_views.AllowedLocationsAPI.as_view(),

    ),

    # ! Trip
    path(
        "trips/all/",
        trip_views.AllTripsAPI.as_view(),
    ),
    path(
        "trips/",
        trip_views.MyTripsAPI.as_view(),
    ),

    path(
        "completed-trips/",
        trip_views.CompletedTripsAPI.as_view(),
    ),

    path(
        "assigned-trips/",
        trip_views.AssignedTripsAPI.as_view(),
    ),
    path(
        "assigned-trips-by-me/",
        trip_views.TripsAssignedByMeAPI.as_view(),
    ),
    path(
        "recent-trips/",
        trip_views.RecentTripsAPI.as_view(),
    ),
    path(
        "trips/<uuid:uuid>/",
        trip_views.TripAPI.as_view(),
    ),
    path(
        "trips/<uuid:uuid>/cancel/",
        trip_views.TripCancelAPI.as_view(),
    ),
    path(
        "trips/<uuid:uuid>/details/",
        trip_details_views.TripDetailsAPI.as_view(),
    ),
    path(
        "trips/<uuid:uuid>/remarks/",
        trip_details_views.TripRemarksAPI.as_view(),
    ),
    path(
        "trips/<uuid:uuid>/scans/",
        trip_details_views.TripScansAPI.as_view(),
    ),
    path(
        "trips/<uuid:uuid>/fuel-cost/",
        trip_details_views.TripFuelCostAPI.as_view(),
    ),
    path(
        "trip-templates/",
        trip_template_views.AllTripTemplatesAPI.as_view(),
    ),
    path(
        "trip-templates/<uuid:uuid>/",
        trip_template_views.TripTemplatesAPI.as_view(),
    ),
    path(
        "search-location/",
        trip_views.SearchLocationAPI.as_view(),
    ),
    # api to get geo code using google map api
    path(
        "get-geocode/",
        trip_views.GetGeoCodeAPI.as_view(),
    ),
    path(
        "ongoing-trip/",
        trip_views.OngoingTripAPI.as_view(),
    ),
    # ! Ride Expense
    path(
        "trips/<uuid:uuid>/ride-expense/",
        expense_views.RideExpenseAPI.as_view(),
    ),
    path(
        "trips/<uuid:uuid>/ride-expense/recall/",
        expense_views.RecallRideExpensesAPI.as_view(),
    ),

    # Save ride exp as draft
    path(
        "trips/<uuid:uuid>/ride-expense/submit/",
        expense_views.SubmitRideExpenseAPI.as_view(),
    ),
    path(
        "trips/<uuid:uuid>/ride-expense/docs/",
        expense_views.RideExpenseDocsAPI.as_view(),
    ),
    path(
        "ride-expenses/all/",
        expense_views.AllRideExpensesAPI.as_view(),
    ),
    path(
        "my-ride-expenses/",
        trip_views.MyRideExpensesAPI.as_view(),
    ),
    path(
        "payment-modes/",
        payment_mode_views.AllPaymentModesAPI.as_view(),
    ),
    path(
        "payment-modes/<uuid:uuid>/",
        payment_mode_views.PaymentModesAPI.as_view(),
    ),
    # ! Approvals
    path("my-approvals/", approval_views.MyApprovalsAPI.as_view()),
    path("reimbursements/", approval_views.MyReimbursementsAPI.as_view()),
    path("approvals/<uuid:uuid>/", approval_views.ApprovalAPI.as_view()),
    # ! Export
    path(
        "export-requests/poll/<uuid:uuid>/",
        export_request_views.PollExportRequestAPI.as_view(),
    ),
    # ======================== only access to admin ========================
    path(
        "all-trips-top-riders/",
        member_report_views.AllTripTopRidersAPI.as_view(),
    ),
    path(
        "all-trips-status-statistics/",
        member_report_views.AllTripStatistics.as_view(),
    ),
    path(
        "all-trips-member-details/",
        member_report_views.AllTripsMemberDetails.as_view(),
    ),
    path(
        "all-ride-expenses-status-statistics/",
        member_report_views.AllRideExpensesStatistics.as_view(),
    ),
    path(
        "all-ride-expenses-top-reimbersement/",
        member_report_views.AllRideExpensesTopReimbersement.as_view(),
    ),
    path(
        "all-ride-expenses-member-details/",
        member_report_views.AllRideExpensesMemberDetails.as_view(),
    ),
    path(
        "all-ride-expenses-statistics-by-yearly/",
        member_report_views.AllRideExpensesMemberDetailsByYearly.as_view(),
    ),
    path(
        "all-trips-member-by-yearly/",
        member_report_views.AllTripsMemberDetailsByYearly.as_view(),
    ),
    path(
        "all-ride-expenses-member-details-csv/",
        member_report_views.AllRideExpensesMemberDetailsCSV.as_view(),
    ),
    path(
        "all-trips-member-details-csv/",
        member_report_views.AllTripMemberDetailsCSV.as_view(),
    ),
    # ======================== only access to admin ========================
    path(
        "department/upload-csv/",
        member_views.DepartmentUploadCSVAPI.as_view(),
    ),
    path(
        "member-fuel-and-vehicle/",
        member_misc_views.GetMemberFuelAndVehicleAPI.as_view(),
    ),
    path(
        "get-trips/",
        trip_views.MyTripsWithUUIDAPI.as_view(),
    ), 

    path(
        "field-report-form-config/",
        form_builder.FieldReportFormConfigAPI.as_view(),
    ),
    path(
        "field-report-form-config/department/<uuid:uuid>/",
        form_builder.DepartmentFieldReportFormConfigAPI.as_view(),
    ),

    path(
        "field-report-form-config/<uuid:uuid>/",
        form_builder.AllFieldReportFormConfigAPI.as_view(),
    ),
    path(
        "field-report-form-config/delete/<uuid:uuid>/",
        form_builder.DelFieldReportFormConfigAPI.as_view(),
    ),


    path(
        "field-report-form-submission/",
        form_submission.FieldReportFormSubmissionsAPI.as_view(),
    ),
    path(
        "field-report-form-submission/<uuid:uuid>/",
        form_submission.AllFieldReportFormSubmissionsAPI.as_view(),
    ),
    path(
        "field-report-form-submission/trip/<uuid:uuid>/",
        form_submission.CheckIsRequiredToSubmitFieldReportAPI.as_view(),
    ),


    path(
        "create-trip-form-config/",
        create_trip_field_report_config.CreateTripFormConfigAPI.as_view(),
    ),
    path(
        "create-trip-form-config/department/<uuid:uuid>/",
        create_trip_field_report_config.DepartmentCreateTripFormConfigAPI.as_view(),
    ),
    path(
        "create-trip-form-config/delete/<uuid:uuid>/",
        create_trip_field_report_config.DelCreateTripFormConfigAPI.as_view(),
    ),

    path(
        "admin-report-form-config/",
        admin_report_form_config.AdminReportFormConfigAPI.as_view(),
    ),
    path(
        "admin-report-form-submission/",
        admin_report_form_config.CreateAdminReportFormConfigAPI.as_view(),
    ),

    path(
        "admin-report-form-config/department/<uuid:uuid>/",
        admin_report_form_config.DepartmentAdminReportFormConfigAPI.as_view(),
    ),
    path(
        "admin-report-form-config/delete/<uuid:uuid>/",
        admin_report_form_config.DelAdminReportFormConfigAPI.as_view(),
    ),

    path(
        "trips/upload-csv/",
        trip_views.TripsUploadCSVAPI.as_view(),
    ),

    path(
        "v2/members/",
        member_views.AllMembersV2API.as_view(),
    ),
    path(
        "v2/departments/",
        org_views.AllDepartmentsV2API.as_view(),
    ),
]
